# Generated by Django 3.2.3 on 2021-07-28 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='street',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.orderitem'),
            preserve_default=False,
        ),
    ]
