# Generated by Django 3.2.3 on 2021-07-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210729_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
