# Generated by Django 3.2.3 on 2021-07-28 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210729_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
    ]
