# Generated by Django 3.2.3 on 2021-07-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210729_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='card_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='card_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
