# Generated by Django 3.2.3 on 2021-07-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orders_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='card_number',
            field=models.CharField(choices=[('Humo', 'Humo'), ('UzCard', 'UzCard'), ('Visa', 'Visa')], default='Visa', max_length=9),
        ),
    ]
