# Generated by Django 3.2.3 on 2021-07-29 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orders_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('Humo', 'Humo'), ('UzCard', 'UzCard'), ('Visa', 'Visa')], default='Visa', max_length=9)),
                ('card_number', models.CharField(max_length=16, null=True)),
                ('exp_date', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='card_type',
        ),
        migrations.AddField(
            model_name='orders',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.cart_details'),
            preserve_default=False,
        ),
    ]
