# Generated by Django 3.2.3 on 2021-07-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210729_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_number',
            field=models.IntegerField(default=1),
        ),
    ]
