# Generated by Django 3.2.3 on 2021-07-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_orders_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_details',
            name='card_type',
            field=models.CharField(default='Card type', max_length=9),
        ),
    ]
