# Generated by Django 3.2.3 on 2021-07-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_cart_details_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_details',
            name='card_type',
            field=models.CharField(default='Card type', max_length=100, null=True),
        ),
    ]
