# Generated by Django 3.2.3 on 2021-07-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_cart_details_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
