# Generated by Django 3.2.3 on 2021-07-29 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_orderitem_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_item',
        ),
        migrations.AddField(
            model_name='cart_details',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.orderitem'),
            preserve_default=False,
        ),
    ]
