# Generated by Django 3.2.3 on 2021-07-29 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20210730_0142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
