# Generated by Django 3.2.3 on 2021-07-29 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0002_product'),
        ('order', '0016_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('paid', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_number', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart_details')),
                ('products', models.ManyToManyField(blank=True, to='Foods.Product')),
            ],
        ),
    ]
