# Generated by Django 3.2.3 on 2021-07-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0002_product'),
        ('order', '0018_auto_20210730_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='products',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total',
        ),
        migrations.CreateModel(
            name='OrderProudcts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('products', models.ManyToManyField(blank=True, to='Foods.Product')),
            ],
        ),
    ]
